In [17]:
import numpy as np
from numpy import linalg as LA
H = -13.6
t = -3
a = np.matrix([[H,t],[t,H]])
print(a)
print("")

w,v=LA.eig(a)
print(w)
print("")
print(v)
print("")


[[-13.6  -3. ]
 [ -3.  -13.6]]

[-10.6 -16.6]

[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]



In [22]:
import numpy as np
from numpy import linalg as LA
H = -13.6
t = -3
a = np.matrix([[H,t,0],[t,H,t],[0,t,H]])
w,v = LA.eig(a)
print(w)
print("")
print(v)

[-17.84264069 -13.6         -9.35735931]

[[ 5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01 -1.04662080e-15 -7.07106781e-01]
 [ 5.00000000e-01  7.07106781e-01  5.00000000e-01]]


In [ ]:
import numpy as np
from numpy import linalg as LA
H = -13.6
t = -3
a = np.matrix([[t,H,t,0],[t,H,t],[0,t,H]])
w,v = LA.eig(a)