In [12]:
#1
import numpy as np
from numpy import linalg as LA


H = -13.6
t = -3
#a->b
a = np.matrix([[0,t],[t,0]])
print("H : ")
print(a)
print("")

w,v=LA.eig(a)
print("eigen value : ")
print(w)
print("")
print("eigen vector : ")
print(v)
print("")


#Are the bonding orbitals symmetric or antisymmetric > yes
#[[ 0.70710678  0.70710678] -> symmetric
#[-0.70710678  0.70710678]] -> antisymmetric


H : 
[[ 0 -3]
 [-3  0]]

eigen value : 
[ 3. -3.]

eigen vector : 
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]



In [4]:
#2
import numpy as np
from numpy import linalg as LA


H = -13.6
t = -3
#a->b
a = np.matrix([[0,t],[t,-5]])
print("H : " ,a)
print("")

w,v=LA.eig(a)
print(w)
print("")
print(v)
print("")

H :  [[ 0 -3]
 [-3 -5]]

[ 1.40512484 -6.40512484]

[[ 0.90558942  0.4241554 ]
 [-0.4241554   0.90558942]]



In [11]:
#3
#three atoms
import numpy as np
from numpy import linalg as LA
H = -13.6
t = -3
print("H : ")
a = np.matrix([[H,t,0],[t,H,t],[0,t,H]])

w,v = LA.eig(a)
print("eigen value : ")
print(w)
print("eigen vector : ")
print(v)

H : 
eigen value : 
[-17.84264069 -13.6         -9.35735931]
eigen vector : 
[[ 5.00000000e-01 -7.07106781e-01  5.00000000e-01]
 [ 7.07106781e-01 -1.04662080e-15 -7.07106781e-01]
 [ 5.00000000e-01  7.07106781e-01  5.00000000e-01]]


In [ ]:
#4
